import { createHash } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { AppError, ERROR_CODES, ensure } from '../../shared/errors.ts';
import { validateBoundedLimit } from '../sandbox/path-policy.ts';
import type {
  ArtifactStorageAdapterWithWriter,
  ArtifactStorageReadRequest,
  ArtifactStorageReadResult,
  ArtifactStorageWriteRequest,
  ArtifactStorageWriteResult,
} from './access.ts';

/**
 * Private immutable object storage for a single VPS deployment. The directory
 * must be mounted as a private volume; keys are generated by the server and
 * never accepted from a browser. Production can replace this adapter with S3,
 * COS or R2 without changing the durable artifact contract.
 */
export class FileSystemArtifactStorageAdapter implements ArtifactStorageAdapterWithWriter {
  private readonly root: string;

  constructor(root: string) {
    ensure(path.isAbsolute(root), 'Artifact storage root must be absolute.', 503, ERROR_CODES.RUNTIME_UNAVAILABLE);
    this.root = path.resolve(root);
  }

  async write(request: ArtifactStorageWriteRequest): Promise<ArtifactStorageWriteResult> {
    validateRequest(request);
    const target = this.resolve(request.storageKey);
    await fs.mkdir(path.dirname(target), { recursive: true, mode: 0o700 });
    const temp = `${target}.tmp-${process.pid}-${Math.random().toString(16).slice(2)}`;
    try {
      await fs.writeFile(temp, request.bytes, { mode: 0o600, flag: 'wx' });
      await fs.rename(temp, target).catch((error: unknown) => {
        if ((error as NodeJS.ErrnoException).code === 'EEXIST') {
          throw new AppError('Artifact object already exists.', 409, ERROR_CODES.RUNTIME_POLICY_DENIED);
        }
        throw error;
      });
      return { storageKey: request.storageKey, objectVersion: request.objectVersion };
    } finally {
      await fs.rm(temp, { force: true }).catch(() => undefined);
    }
  }

  async read(request: ArtifactStorageReadRequest): Promise<ArtifactStorageReadResult> {
    ensure(request.storageKey.length > 0, 'Artifact storage key is invalid.', 409, ERROR_CODES.RUNTIME_POLICY_DENIED);
    validateBoundedLimit(request.maxBytes, 32 * 1024 * 1024, 'artifact read limit');
    const target = this.resolve(request.storageKey);
    const stat = await fs.stat(target).catch(() => null);
    ensure(stat?.isFile() === true, 'Artifact object not found.', 404, ERROR_CODES.RESOURCE_NOT_FOUND);
    ensure(stat.size <= request.maxBytes, 'Artifact object exceeds the permitted read limit.', 413, ERROR_CODES.REQUEST_BODY_TOO_LARGE);
    const bytes = new Uint8Array(await fs.readFile(target));
    ensure(bytes.byteLength === stat.size, 'Artifact object changed while reading.', 409, ERROR_CODES.RUNTIME_POLICY_DENIED);
    return { bytes, objectVersion: request.objectVersion };
  }

  async remove(request: Pick<ArtifactStorageWriteRequest, 'storageKey' | 'objectVersion'>): Promise<void> {
    this.resolve(request.storageKey);
    await fs.rm(this.resolve(request.storageKey), { force: true });
  }

  private resolve(storageKey: string): string {
    ensure(storageKey.length > 0 && storageKey.length <= 512, 'Artifact storage key is invalid.', 409, ERROR_CODES.RUNTIME_POLICY_DENIED);
    ensure(!storageKey.startsWith('/') && !storageKey.includes('\\') && !storageKey.includes('\0'), 'Artifact storage key is invalid.', 409, ERROR_CODES.RUNTIME_POLICY_DENIED);
    const target = path.resolve(this.root, ...storageKey.split('/'));
    const base = `${path.resolve(this.root)}${path.sep}`;
    ensure(target.startsWith(base), 'Artifact storage key escapes the storage root.', 409, ERROR_CODES.RUNTIME_POLICY_DENIED);
    return target;
  }
}

export function createArtifactStorageKey(ownerId: string, bundleId: string, artifactId: string, sha256: string): string {
  const safe = [ownerId, bundleId, artifactId].every((value) => /^[A-Za-z0-9][A-Za-z0-9_-]{0,159}$/u.test(value));
  ensure(safe, 'Artifact storage identity is invalid.', 409, ERROR_CODES.RUNTIME_POLICY_DENIED);
  ensure(/^sha256:[a-f0-9]{64}$/u.test(sha256), 'Artifact digest is invalid.', 409, ERROR_CODES.RUNTIME_POLICY_DENIED);
  return `bundles/${ownerId}/${bundleId}/${artifactId}-${sha256.slice('sha256:'.length, 24)}.blob`;
}

export function objectVersionForBytes(bytes: Uint8Array): string {
  return `v1-${createHash('sha256').update(bytes).digest('hex').slice(0, 40)}`;
}

function validateRequest(request: ArtifactStorageWriteRequest): void {
  ensure(request.bytes instanceof Uint8Array && request.bytes.byteLength > 0, 'Artifact bytes are invalid.', 400, ERROR_CODES.REQUEST_VALIDATION_FAILED);
  ensure(request.objectVersion.length > 0 && !/^(latest|current|head|main|master)$/u.test(request.objectVersion), 'Artifact object version is invalid.', 409, ERROR_CODES.RUNTIME_POLICY_DENIED);
}
