'use client';
import { useState,useEffect,useRef } from 'react';
import Link from 'next/link';
import { useRouter,useSearchParams } from 'next/navigation';
import dynamic from 'next/dynamic';
import { useBuilderStore } from './store';
import { Icon,Loading,ErrorNotice,GradeList,useData,useSession,useToast,LaneNote } from '@/components/common';
import { Button } from '@/components/ui/button';
import { api,post,consumeRun } from '@/lib/client-api';
import { validateWorkflow } from '@/lib/workflow/validate';
import { SKILLS,TOOLS,NODE_LABELS,JSON_SCHEMA,ROUTES } from '@/shared/catalog';
import type { Config,NodeKind,RunEvent,CaseResult,RunSummary,Trace } from '@/shared/types';
import { money,number,duration,cn } from '@/lib/utils';
const WorkflowCanvas=dynamic(()=>import('./canvas').then(m=>m.WorkflowCanvas),{ssr:false,loading:()=> <Loading/>});
const NODE_ICONS:Record<NodeKind,string>={input:'ArrowDownToLine',prompt:'Code2',model:'Cpu',skill:'Sparkles',tool:'Wrench',validator:'ShieldCheck',output:'ArrowUpFromLine'};
const NODES=Object.keys(NODE_LABELS) as NodeKind[];
function CodeEditor({value,onChange,label,placeholder,rows=7}:{value:string;onChange:(v:string)=>void;label:string;placeholder?:string;rows?:number}){
 const toast=useToast();return <div className="field"><div className="flex justify-between items-center mb-1"><label className="label">{label}</label><button className="button ghost small" aria-label={`Copy ${label}`} onClick={()=>{navigator.clipboard.writeText(value).then(()=>toast('Copied to clipboard.')).catch(()=>toast('Clipboard is unavailable.',true));}}><Icon name="Copy" size={11}/></button></div><div className="code-editor"><div className="line-numbers" aria-hidden="true">{value.split('\n').map((_,i)=><span key={i}>{i+1}</span>)}</div><textarea aria-label={label} spellCheck={false} value={value} onChange={e=>onChange(e.target.value)} maxLength={8000} placeholder={placeholder} rows={rows}/></div><div className="prompt-footer"><span>{value.length.toLocaleString()} chars</span><span>~{Math.ceil(new TextEncoder().encode(value).length/4)} tokens / estimate</span></div></div>;
}
function SchemaEditor({schema,update}:{schema:Record<string,unknown>|undefined;update:(schema:Record<string,unknown>)=>void}){
 const [text,setText]=useState(JSON.stringify(schema||JSON_SCHEMA,null,2)),[error,setError]=useState('');useEffect(()=>setText(JSON.stringify(schema||JSON_SCHEMA,null,2)),[schema]);return <><CodeEditor label="JSON Schema" value={text} rows={9} onChange={v=>{setText(v);try{const parsed=JSON.parse(v);if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw Error();update(parsed);setError('');}catch{setError('Invalid JSON. The last valid schema is still active.');}}}/>{error&&<div className="error-text">{error}</div>}</>;
}
function Inspector({providers,problem,revision}:{providers:any;problem:any;revision:number}){
 const store=useBuilderStore(),node=store.nodes.find(n=>n.id===store.selectedId);if(!node)return <aside className="config-panel"><div className="panel-eyebrow">NODE CONFIGURATION</div><div className="build-inspector-empty"><Icon name="SlidersHorizontal" size={25}/><p className="mt-2">Select a node to tune its behavior.<br/>Connect the handles to change your strategy.</p></div></aside>;
 const {kind,config:c}=node.data;const update=(v:Partial<Config>)=>store.update(node.id,v);const fields=providers?.credentials||[];
 return <aside className="config-panel"><div className="panel-eyebrow flex justify-between">{kind.toUpperCase()} CONFIG<span className="dim">v{revision||1}</span></div><div className="config-body"><div className="inspector-node-title"><span className={`component-icon ${kind}`}><Icon name={NODE_ICONS[kind]}/></span><span>{node.data.label}</span></div><div className="field"><label className="label">Node name</label><input value={node.data.label} maxLength={80} onChange={e=>store.update(node.id,{},e.target.value)}/></div>
 {kind==='prompt'&&<><CodeEditor label="System prompt" value={c.systemPrompt||''} onChange={systemPrompt=>update({systemPrompt})}/><CodeEditor label="User template" value={c.userTemplate||''} onChange={userTemplate=>update({userTemplate})} rows={3}/><p className="helper">Variables: {'{{input}}'} and {'{{previous}}'}. Inputs are data, never executable code.</p><Button variant="ghost" size="sm" onClick={()=>{const original=problem?.starter?.nodes.find((n:any)=>n.kind==='prompt');if(original)update(original.config);}}><Icon name="RotateCcw" size={12}/>Reset to mission starter</Button></>}
 {kind==='model'&&<><div className="field"><label className="label">Provider</label><select aria-label="Node provider" value={c.credentialId||'demo'} onChange={e=>{const id=e.target.value,provider=fields.find((p:any)=>p.id===id);update({credentialId:id,modelId:id==='demo'?'demo-forge':id==='platform'?providers.platform.modelId:provider?.modelId||''});}}>{providers?.demo&&<option value="demo">Demo simulator / no API cost</option>}{providers?.platform&&<option value="platform">Platform AI Gateway</option>}{fields.map((p:any)=><option key={p.id} value={p.id}>{p.name} / {p.keyMask}</option>)}{!providers&&<option value="demo">Demo simulator</option>}</select></div><div className="field"><label className="label">Model ID</label><input value={c.modelId||''} disabled={c.credentialId==='demo'||c.credentialId==='platform'} maxLength={160} onChange={e=>update({modelId:e.target.value})}/></div><div className="form-grid"><div className="field"><label className="label">Max output tokens</label><input type="number" min={16} max={8192} value={c.maxTokens||512} onChange={e=>update({maxTokens:Number(e.target.value)})}/></div><div className="field"><label className="label">Temperature</label><input type="number" min={0} max={2} step={.1} value={c.temperature??0} onChange={e=>update({temperature:Number(e.target.value)})}/></div></div><div className="callout small">Demo results are simulated. BYOK runs use your key and are ranked separately.</div><Link href="/providers" className="section-link mt-3"><Icon name="Settings" size={12}/> Manage encrypted credentials</Link></>}
 {kind==='skill'&&<><div className="field"><label className="label">Skill card</label><select value={c.skillId||'structured'} onChange={e=>update({skillId:e.target.value as Config['skillId']})}>{SKILLS.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></div><p className="helper mb-3">{SKILLS.find(s=>s.id===c.skillId)?.description}</p>{c.skillId==='structured'&&<SchemaEditor schema={c.schema} update={schema=>update({schema})}/>} {c.skillId==='concise'&&<div className="field"><label className="label">Maximum output characters</label><input type="number" min={1} max={8000} value={c.maxLength||300} onChange={e=>update({maxLength:Number(e.target.value)})}/></div>}<div className="callout small">Place skills before a Model. Reflection and Retry can each add a bounded model call; all calls count toward your energy budget.</div></>}
 {kind==='tool'&&<><div className="field"><label className="label">Registered tool</label><select value={c.toolId||'json-validator'} onChange={e=>update({toolId:e.target.value as Config['toolId']})}>{TOOLS.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></div><p className="helper mb-3">{TOOLS.find(t=>t.id===c.toolId)?.description}</p>{c.toolId==='json-validator'&&<SchemaEditor schema={c.schema} update={schema=>update({schema})}/>} {(['calculator','text-search','string-matcher'] as string[]).includes(c.toolId||'')&&<div className="field"><label className="label">{c.toolId==='calculator'?'Expression / blank = previous output':c.toolId==='text-search'?'Search query':'Text to match'}</label><input value={c.toolId==='calculator'?c.expression||'':c.toolId==='text-search'?c.query||'':c.match||''} maxLength={1000} onChange={e=>update({[c.toolId==='calculator'?'expression':c.toolId==='text-search'?'query':'match']:e.target.value})}/></div>}<div className="callout small">Before Model: equips a tool for AI tool calling. After Model: executes the configured tool on the previous output. No shell or arbitrary code.</div></>}
 {kind==='validator'&&<><div className="field"><label className="label">Output contract</label><select value={c.format||'json'} onChange={e=>{const format=e.target.value as Config['format'];update({format,schema:format==='json'?JSON_SCHEMA:undefined,values:format==='enum'?ROUTES:undefined});}}><option value="json">JSON Schema</option><option value="enum">Exact enum</option><option value="text">Nonempty text</option></select></div>{(c.format||'json')==='json'&&<SchemaEditor schema={c.schema} update={schema=>update({schema})}/>} {c.format==='enum'&&<CodeEditor label="Allowed values (one per line)" rows={5} value={(c.values||ROUTES).join('\n')} onChange={v=>update({values:v.split('\n').filter(Boolean)})}/>}<p className="helper">A failed validator fails the case even when the final output happens to match.</p></>}
 {kind==='input'&&<div className="callout small">The test runner provides each case as input. Hidden inputs stay on the server and are not editable here.</div>}
 {kind==='output'&&<div className="callout small">The final text from this node is passed to the deterministic judge. Connect a Model upstream.</div>}
 <div className="divider"/><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>store.duplicate(node.id)}><Icon name="Copy" size={12}/>Duplicate</Button><Button variant="ghost" size="sm" className="danger-text" onClick={()=>store.remove(node.id)}><Icon name="Trash2" size={12}/>Delete</Button></div><p className="helper mt-2">Deleting a node removes its edges. Reconnect the path before running.</p></div></aside>;
}
export function BuilderPage(){
 const router=useRouter(),query=useSearchParams(),toast=useToast(),{user,loading:authLoading}=useSession(),store=useBuilderStore();
 const [problem,setProblem]=useState<any>(null),[build,setBuild]=useState<any>(null),[title,setTitle]=useState(''),[visibility,setVisibility]=useState<'public'|'private'>('private'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false),[running,setRunning]=useState(false),[kind,setKind]=useState<'public'|'hidden'>('public'),[tab,setTab]=useState('results'),[cases,setCases]=useState<CaseResult[]>([]),[traces,setTraces]=useState<(Trace&{caseNumber:number})[]>([]),[summary,setSummary]=useState<RunSummary|null>(null),[progress,setProgress]=useState({completed:0,total:0}),[consent,setConsent]=useState(false);
 const controller=useRef<AbortController|null>(null),loaded=useRef('');const {data:providers}=useData(user?'providers':null);
 const buildId=query.get('build'),problemId=query.get('problem')||'messy-json-extractor',version=query.get('version'),skill=query.get('skill');
 useEffect(()=>{const key=`${buildId}:${problemId}:${version}`;if(loaded.current===key)return;let active=true;setLoading(true);setError('');(async()=>{try{let b:any=null,p:any;if(buildId){b=await api(`builds/${buildId}${version?`?version=${encodeURIComponent(version)}`:''}`);if(!b.owner)throw new Error('This build is read-only. Open its detail page and Fork it first.');p=await api(`problems/${b.problem.slug}`);}else p=await api(`problems/${problemId}`);if(!active)return;loaded.current=key;setProblem(p);setBuild(b);setTitle(b?.title||`${p.title} / my build`);setVisibility(b?.visibility||'private');useBuilderStore.getState().load(b?.workflow||p.starter);if(!b&&SKILLS.some(s=>s.id===skill))useBuilderStore.getState().add('skill',undefined,skill as Config['skillId'],true);setSummary(null);setCases([]);setTraces([]);}catch(e){if(active)setError((e as Error).message);}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[buildId,problemId,version,skill]);
 useEffect(()=>()=>controller.current?.abort(),[]);
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(useBuilderStore.getState().dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before);},[]);
 const real=store.nodes.some(n=>n.data.kind==='model'&&n.data.config.credentialId!=='demo');
 async function save(){if(!user){router.push(`/login?next=${encodeURIComponent(`/builder?${query}`)}`);throw new Error('Sign in before saving a build.');}const workflow=validateWorkflow(store.exportWorkflow());if(build&&!store.dirty&&title===build.title&&visibility===build.visibility&&build.version.id===build.currentVersionId)return build;setSaving(true);try{const saved=await post('builds',{...(build?{buildId:build.id,currentVersionId:build.currentVersionId}:{}),problemId:problem.id,title,visibility,workflow});setBuild(saved);useBuilderStore.setState({dirty:false});toast(`Saved immutable version ${saved.version.revision}.`);loaded.current=`${saved.id}:${problem.slug}:null`;window.history.replaceState(null,'',`/builder?build=${saved.id}&problem=${problem.slug}`);return saved;}finally{setSaving(false);}}
 async function run(runKind:'public'|'hidden'){setError('');if(real&&!consent){setError('Confirm provider usage below before running a real model.');return;}setRunning(true);setKind(runKind);setTab(runKind==='public'?'trace':'results');setCases([]);setTraces([]);setSummary(null);setProgress({completed:0,total:0});store.clearTrace();controller.current=new AbortController();try{const saved=await save();await consumeRun({buildId:saved.id,kind:runKind,consent},(event:RunEvent)=>{if(event.type==='start')setProgress({completed:0,total:event.total});if(event.type==='trace'){store.trace(event.trace.nodeId,event.trace.state,event.trace.tokens);setTraces(t=>[...t.slice(-199),{...event.trace,caseNumber:event.caseNumber}]);}if(event.type==='case')setCases(c=>[...c,event.result]);if(event.type==='progress')setProgress({completed:event.completed,total:event.total});if(event.type==='complete'){setSummary(event.summary);setTab('results');toast(runKind==='hidden'?`Submitted. ${event.summary.score.total} points in the ${event.summary.tier} lane.`:'Public test run complete.');}if(event.type==='error')throw new Error(event.message);},controller.current.signal);}catch(e){setError((e as Error).name==='AbortError'?'Run cancelled. Completed provider calls may still be billed.':(e as Error).message);}finally{setRunning(false);}}
 const exportJson=()=>{const blob=new Blob([JSON.stringify(store.exportWorkflow(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='agentforge-workflow.json';a.click();URL.revokeObjectURL(url);toast('Workflow exported. API key values are never part of the workflow.');};
 if(loading||authLoading)return <Loading/>;if(!problem)return <main className="container page"><ErrorNotice message={error||'Challenge unavailable.'}/><Link href="/challenges" className="button outline mt-3">Back to missions</Link></main>;
 return <main className="builder-page"><div className="builder-toolbar"><div className="builder-title"><div className="breadcrumb"><Link href={`/challenges/${problem.slug}`}>{problem.title}</Link><Icon name="ChevronRight" size={10}/><span>AGENT BUILDER</span></div><div className="flex items-center gap-2"><input aria-label="Build name" value={title} maxLength={80} onChange={e=>setTitle(e.target.value)}/><span className="chip">v{build?.version.revision||1}{store.dirty?' *':''}</span></div></div><div className="toolbar-actions"><select aria-label="Build visibility" value={visibility} onChange={e=>setVisibility(e.target.value as 'public'|'private')}><option value="private">Secret prompt</option><option value="public">Public prompt</option></select><Button variant="ghost" size="icon" title="Export workflow JSON" onClick={exportJson}><Icon name="Download"/></Button><Button variant="outline" disabled={saving||running} onClick={()=>save().catch(e=>setError(e.message))}><Icon name="Save" size={14}/>{saving?'Saving...':'Save'}</Button>{running?<Button variant="outline" onClick={()=>controller.current?.abort()}><Icon name="X"/>Cancel</Button>:<Button variant="outline" onClick={()=>run('public')}><Icon name="Play" size={14}/>Run public tests</Button>}<Button disabled={running||saving} onClick={()=>run('hidden')}><Icon name="Send" size={14}/>Submit</Button></div></div>
 {error&&<div className="builder-error"><ErrorNotice message={error}/></div>}{real&&<label className="callout small mb-2 flex items-center gap-2"><input type="checkbox" style={{width:15}} checked={consent} onChange={e=>setConsent(e.target.checked)}/>I authorize token charges and sending test inputs to this provider. A user-controlled gateway is not a trusted hidden benchmark.</label>}
 <div className="builder-grid"><aside className="palette"><div className="panel-eyebrow">COMPONENTS<span className="dim">7</span></div><div className="palette-body"><div className="eyebrow mb-2">DRAG TO CANVAS</div>{NODES.map(kind=><button draggable onDragStart={e=>e.dataTransfer.setData('application/agentforge',kind)} className="palette-item" key={kind} onClick={()=>store.add(kind)}><span className={`component-icon ${kind}`}><Icon name={NODE_ICONS[kind]} size={14}/></span><span>{NODE_LABELS[kind]}</span><Icon name="Plus" size={11}/></button>)}<div className="divider"/><div className="eyebrow mb-2">QUICK EQUIP</div><p className="helper mb-2">Insert a skill before the model.</p>{SKILLS.map(s=><button className="equip-card" key={s.id} onClick={()=>store.add('skill',undefined,s.id,true)} title={s.description}><Icon name={s.icon} size={12}/><span>{s.name}</span><Icon name="Plus" size={10}/></button>)}<div className="palette-hint"><Icon name="GitFork" size={13}/><p>Connect output handles to input handles. A valid path needs Input, Model, and Output.</p></div></div><div className="palette-footer"><Icon name="ShieldCheck" size={12}/> Controlled tools only</div></aside><section className="canvas-panel"><div className="canvas-toolbar"><span><span className="status-dot"/> {running?'EXECUTING':'WORKFLOW CANVAS'}</span><span>{store.nodes.length} NODES / {store.edges.length} EDGES</span></div><WorkflowCanvas/><div className="canvas-shortcuts"><span>Drag to move / scroll to zoom / Backspace to delete</span><span>{number(problem.constraints.tokenBudget)} ENERGY MAX</span></div></section><Inspector providers={providers} problem={problem} revision={build?.version.revision||1}/>
 <section className="run-console" aria-live="polite"><div className="console-header"><Icon name="Terminal" size={14}/>{[['results','TEST RESULTS'],['trace','EXECUTION TRACE'],['energy','ENERGY']].map(([id,label])=><button key={id} className={cn('console-tab',tab===id&&'active')} onClick={()=>setTab(id)}>{label}{id==='results'&&cases.length>0?` (${cases.filter(c=>c.passed).length}/${cases.length})`:''}</button>)}<span className="mono small dim" style={{marginLeft:'auto'}}>{running?<><span className="spinner"/> {progress.completed}/{progress.total}</>:summary?`${summary.tier.toUpperCase()} / ${kind==='hidden'?'SUBMITTED':'PUBLIC'}`:'READY'}</span></div>{running&&<div className="run-progress"><span style={{width:`${progress.total?progress.completed/progress.total*100:3}%`}}/></div>}<div className="console-body">
 {summary&&(tab==='results'||tab==='energy')&&<><div className="console-score"><div><div className="eyebrow">{kind==='hidden'?'ARENA SCORE':'PRACTICE SCORE'}</div><div className="score-large">{summary.score.total}<small>/1000</small></div><div className="score-verdict"><b className="accent">{summary.passed}</b> / {summary.total} tests passed</div>{kind==='hidden'&&<Link href={`/leaderboard?problem=${problem.id}&tier=${summary.tier}`} className="section-link mt-2">View leaderboard <Icon name="ArrowUpRight" size={11}/></Link>}</div><GradeList score={summary.score}/><div className="energy-breakdown"><div><label>Prompt</label><span>{number(summary.metrics.inputTokens)} tokens</span></div><div><label>Reasoning</label><span>{number(summary.metrics.reasoningTokens)} tokens</span></div><div><label>Visible output</label><span>{number(Math.max(0,summary.metrics.outputTokens-summary.metrics.reasoningTokens))} tokens</span></div><div><label>Total energy</label><b className="accent">{number(summary.metrics.inputTokens+summary.metrics.outputTokens)}</b></div><div><label>Tool calls / all cases</label><span>{summary.metrics.toolCalls}</span></div><div><label>{summary.tier==='demo'?'Simulated cost':'Estimated cost'}</label><span>{money(summary.metrics.cost)}</span></div><div><label>Summed execution time</label><span>{duration(summary.metrics.latency)}</span></div></div></div><div className="divider"/></>}
 {tab==='results'&&kind==='public'&&cases.map((c,i)=><details className="case-result" key={c.caseId} open={!c.passed}><summary><span className={cn('result-status',c.passed?'accent':'danger-text')}>{c.passed?'PASS':'FAIL'}</span><span>Case {i+1} / {c.category}</span><span className="dim mono" style={{marginLeft:'auto'}}>{duration(c.latency)} / {number(c.inputTokens+c.outputTokens)} tokens</span><Icon name="ChevronDown" size={12}/></summary><div className="case-details"><div style={{gridColumn:'1/3'}}><span className="eyebrow">INPUT</span><pre>{c.input}</pre></div><div><span className="eyebrow">EXPECTED</span><pre>{JSON.stringify(c.expected,null,2)}</pre></div><div><span className="eyebrow">ACTUAL</span><pre>{c.actual}</pre></div><div className="case-stats"><span>INPUT: {c.inputTokens}</span><span>OUTPUT: {c.outputTokens}</span><span>COST: {money(c.cost)}</span><span>{c.failureType||'Contract passed'}</span></div></div></details>)}
 {tab==='results'&&kind==='hidden'&&(summary||running)&&<><div className="callout small"><Icon name="Lock" size={13}/>Hidden inputs, expected outputs, traces, and actual model answers are not returned. {running?'The server is judging the sealed suite.':'Only aggregate results are available.'}</div>{summary&&<><div className="flex gap-3 wrap mt-3">{Object.entries(summary.failures).map(([name,count])=><span className="chip" key={name}>{name}: {count}</span>)}{!Object.keys(summary.failures).length&&<span className="chip green">ALL CONTRACTS PASSED</span>}</div><div className="mt-3"><LaneNote tier={summary.tier}/></div></>}</>}
 {tab==='trace'&&<div className="console-traces">{traces.map((t,i)=><div className="trace-line" key={i}><span className="dim">{String(i+1).padStart(3,'0')}</span><span className={t.state==='failed'?'danger-text':'accent'}>{t.state==='running'?'RUN ':t.state==='done'?'DONE':'FAIL'}</span><span className="node-label">{t.label}</span><span className="dim">case {t.caseNumber}</span><span className="trace-token">{t.tokens===undefined?'':`${t.tokens} tokens`}{t.latency===undefined?'':` / ${duration(t.latency)}`}</span></div>)}{!traces.length&&<p className="dim">{kind==='hidden'?'Hidden execution traces stay server-side.':'Run public tests to watch the agent execute each node.'}</p>}</div>}
 {!running&&!summary&&!cases.length&&tab!=='trace'&&<div className="console-welcome"><Icon name="Terminal"/><div><strong>Your agent is ready for its first run.</strong><p>Start with public tests. Tune your prompt. Then challenge the hidden suite.</p></div></div>}
 {running&&!cases.length&&!summary&&tab!=='trace'&&<div className="console-welcome"><span className="spinner"/><div><strong>{kind==='hidden'?'The judge is running the hidden suite.':'Your workflow is executing.'}</strong><p>{progress.completed} of {progress.total} cases completed.</p></div></div>}
 </div></section></div></main>;
}
