'use client';
import { createContext,useContext,useEffect,useState,useCallback,type ReactNode } from 'react';
import Link from 'next/link';
import { ArrowRight,ArrowUpRight,Braces,ShieldCheck,Shield,Inbox,Boxes,Activity,Users,Zap,Trophy,GitFork,ArrowDownToLine,ArrowUpFromLine,Cpu,Sparkles,Wrench,Timer,Lock,Plus,Settings,LogOut,Play,Save,Copy,RotateCcw,Trash2,ChevronRight,Search,Code2,Terminal,Target,Check,AlertTriangle,Orbit,Crosshair,Minimize2,ScanText,ScanEye,Calculator,Calendar,WholeWord,Globe,ExternalLink,BookOpen,Eye,EyeOff,SlidersHorizontal,FileJson,Send,Download,X,Github,ChevronDown,CheckCircle2 } from 'lucide-react';
import { api } from '@/lib/client-api';
import { money,number,percent,cn } from '@/lib/utils';
const ICONS={ArrowRight,ArrowUpRight,Braces,ShieldCheck,Shield,Inbox,Boxes,Activity,Users,Zap,Trophy,GitFork,ArrowDownToLine,ArrowUpFromLine,Cpu,Sparkles,Wrench,Timer,Lock,Plus,Settings,LogOut,Play,Save,Copy,RotateCcw,Trash2,ChevronRight,Search,Code2,Terminal,Target,Check,AlertTriangle,Orbit,Crosshair,Minimize2,ScanText,ScanEye,Calculator,Calendar,WholeWord,Globe,ExternalLink,BookOpen,Eye,EyeOff,SlidersHorizontal,FileJson,Send,Download,X,Github,ChevronDown,CheckCircle2};
export function Icon({name,size=16,className=''}:{name:string;size?:number;className?:string}){const Component=ICONS[name as keyof typeof ICONS]||Boxes;return <Component size={size} className={className} aria-hidden="true"/>;}
export const ToastContext=createContext<(message:string,error?:boolean)=>void>(()=>{});
export function ToastProvider({children}:{children:ReactNode}){const [toasts,set]=useState<{id:number;message:string;error:boolean}[]>([]);const notify=useCallback((message:string,error=false)=>{const id=Date.now()+Math.random();set(v=>[...v.slice(-2),{id,message,error}]);setTimeout(()=>set(v=>v.filter(t=>t.id!==id)),4800);},[]);return <ToastContext.Provider value={notify}>{children}<div className="toast-container" aria-live="polite">{toasts.map(t=><div key={t.id} className={cn('toast',t.error&&'error')}>{t.message}</div>)}</div></ToastContext.Provider>;}
export const useToast=()=>useContext(ToastContext);
export const SessionContext=createContext<{user:any;loading:boolean;boot:any}>({user:null,loading:true,boot:null});
export const useSession=()=>useContext(SessionContext);
export function useData<T=any>(path:string|null){const [data,setData]=useState<T|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(!!path),[revision,setRevision]=useState(0);useEffect(()=>{if(!path){setLoading(false);return;}const controller=new AbortController();setLoading(true);setError('');api<T>(path,{signal:controller.signal}).then(d=>{setData(d);setLoading(false);}).catch(e=>{if(!controller.signal.aborted){setError(e.message);setLoading(false);}});return()=>controller.abort();},[path,revision]);return {data,error,loading,reload:()=>setRevision(v=>v+1)};}
export function Avatar({name,index=3,large=false}:{name:string;index?:number;large?:boolean}){return <span className={cn('avatar',`rank-${index}`,large&&'large')}>{name.slice(0,2).toUpperCase()}</span>;}
export function Empty({title,description,action}:{title:string;description:string;action?:ReactNode}){return <div className="empty-state"><Icon name="Boxes"/><h3>{title}</h3><p>{description}</p>{action}</div>;}
export function Loading(){return <div className="loading-state"><div className="flex items-center gap-2"><span className="spinner"/>Loading the arena...</div></div>;}
export function ErrorNotice({message,retry}:{message:string;retry?:()=>void}){return <div className="callout danger"><Icon name="AlertTriangle"/>{message}{retry&&<button className="button small outline" style={{marginLeft:15}} onClick={retry}>Try again</button>}</div>;}
export function PageHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description?:string;action?:ReactNode}){return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</div>;}
export function SectionHeading({title,count,href,link='View all'}:{title:string;count?:number;href?:string;link?:string}){return <div className="section-heading"><div className="heading-label"><h2>{title}</h2>{count!==undefined&&<span className="count">{count}</span>}</div>{href&&<Link href={href} className="section-link">{link}<Icon name="ArrowUpRight"/></Link>}</div>;}
export const problemIcon=(p:any)=>p.judge==='json'?'Braces':p.judge==='enum'?'Inbox':'ShieldCheck';
export function ChallengeCard({problem:p}:{problem:any}){return <Link className="card challenge-card" href={`/challenges/${p.slug}`}><div className="flex items-center justify-between"><div className={cn('icon-box',p.judge==='secret'?'purple':p.judge==='enum'?'amber':'')}><Icon name={problemIcon(p)}/></div><span className={cn('chip',p.worldBoss?'purple':'subtle')}>{p.worldBoss?'WORLD BOSS':p.category}</span></div><h3>{p.title}</h3><p className="line-clamp">{p.description}</p><div className="card-stats"><div><label>Best score</label><strong className="accent">{p.stats.bestScore}<span className="dim"> / 1K</span></strong></div><div><label>Builders</label><strong>{number(p.stats.participants)}</strong></div><div><label>Solve rate</label><strong>{percent(p.stats.solveRate)}</strong></div></div><div className="card-budget"><span><Icon name="Zap"/>{number(p.constraints.tokenBudget)} tokens</span><span><Icon name="Wrench"/>{p.constraints.toolCallLimit} tools</span></div><div className="card-footer"><div className={cn('difficulty',p.difficulty==='Expert'&&'expert')}>{[0,1,2,3].map(i=><i key={i} className={i<(p.difficulty==='Starter'?1:p.difficulty==='Expert'?4:2)?'on':''}/>)}<span>{p.difficulty}</span></div><span className="small muted">+{p.reward} REP <span className="accent">&#8599;</span></span></div></Link>;}
export function LaneNote({tier='demo'}:{tier?:string}){return <div className={cn('callout',tier==='demo'?'purple':tier==='byok'?'warning':'')}><Icon name={tier==='verified'?'ShieldCheck':tier==='demo'?'Sparkles':'AlertTriangle'}/>{tier==='demo'?'Simulation lane. Seeded builds and demo runs are illustrative, not measured model benchmarks.':tier==='byok'?'BYOK / unverified lane. Your provider receives test prompts and can observe them; these results are not trusted rankings.':'Verified lane. Runs use the platform-configured model and administrator-provided pricing.'}</div>;}
export function GradeList({score}:{score:any}){return <div className="grade-list">{['accuracy','robustness','security','efficiency','elegance'].map(k=><div className="grade-row" key={k}><span className="grade-label">{k[0].toUpperCase()+k.slice(1)}</span><div className="grade-bar"><span style={{width:`${score[k]*100}%`}}/></div><strong>{score.grades?.[k]||'-'}</strong></div>)}</div>;}
export function LeaderTable({rows}:{rows:any[]}){return rows.length?<div className="table-wrap"><table className="arena-table"><thead><tr>{['#','Build / Player','Score','Accuracy','Cost / case','Energy / case','Nodes','Engine','Submitted'].map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id}><td className={cn('rank',i<3&&'top')}>{String(r.rank||i+1).padStart(2,'0')}</td><td><div className="flex items-center gap-2"><Avatar name={r.creator.name} index={i}/><div><Link href={`/builds/${r.buildId}?version=${r.versionId}`} className="build-name">{r.title}</Link><div className="player-name"><Link href={`/profile/${r.creator.id}`}>{r.creator.name}</Link>{r.creator.isSeed?' / SEED':''}</div></div></div></td><td className="score">{r.score}</td><td className="num">{percent(r.accuracy)}</td><td className="num">{money(r.cost)}</td><td className="num">{number(r.tokens)}</td><td className="num">{r.nodes}</td><td className="mono small muted">{r.model}</td><td className="mono small dim">{new Date(r.createdAt).toLocaleDateString('en-GB',{month:'short',day:'2-digit'})}</td></tr>)}</tbody></table></div>:<div className="card"><Empty title="The podium is open." description="No eligible submissions in this lane yet. Build an agent and set the first benchmark." action={<Link className="button primary" href="/challenges">Find a challenge <Icon name="ArrowRight"/></Link>}/></div>;}
export function Footer(){return <footer className="site-footer"><span>AGENTFORGE <span className="dim">/</span> BUILD AI. BEAT PROBLEMS.</span><span>Community infrastructure, one build at a time.</span></footer>;}
